name: Public Tests
permissions: read-all

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-public:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: test
        run: echo "Running Public Test"
